[package]
name = "orx-soa-derive"
version = "0.1.0"
edition = "2024"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "Proc macros for deriving soa collections"
license = "MIT OR Apache-2.0"
repository = "https://github.com/orxfun/orx-soa-derive/"
keywords = ["vec", "array", "vector", "soa"]
categories = ["data-structures", "algorithms", "no-std"]

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2", features = ["full"] }
